### ISSUE TITLE
Undercover::Report warning

### ISSUE THREAD

**Issue by paul** [grodowski/pronto-undercover#8]
When I run undercover directly, I get no warnings, but when I use pronto-undercover, I see:

> Undercover::Report#build_warnings is deprecated! Please use the #flagged_results accessor instead.

Looks like it was deprecated in undercover 0.3.4: https://github.com/grodowski/undercover/commit/6a35e2aceb6112ac8c7f2fab5982f1e57c8766e4

**Comment by grodowski** [comment]
Thanks for reporting @paul, this got addressed in `v0.1.5`
